### ISSUE TITLE
Please release v2.0.1 to packagist 

### ISSUE THREAD

**Issue by kesselb** [DeepDiver1975/PHPZipStreamer#15]
Hello :wave: 

v2.0.1 is unfortunately not available on https://packagist.org/packages/deepdiver/zipstreamer.

**Comment by DeepDiver1975** [comment]
@kesselb let me know if this works properly for you now: https://packagist.org/packages/deepdiver/zipstreamer#v2.0.2

**Comment by kesselb** [comment]
@DeepDiver1975 works, thank you very much :+1:
